export const conversationActions = {
    SET_CONVERSATION: 'CONVERSATION.SET_CONVERSATION',
    SET_SELECT_CONVERSATION: 'CONVERSATION.SET_SELECT_CONVERSATION',
    SEND_NEW_MESSAGE: 'CONVERSATION.SEND_NEW_MESSAGE',
    SET_STATUS_WATCHED_FOR_MESSAGES: 'CONVERSATION.SET_STATUS_WATCHED_FOR_MESSAGES',
    SET_STATUS_SENT_FOR_MESSAGES: 'CONVERSATION.SET_STATUS_SENT_FOR_MESSAGES',
    SET_STATUS_RECEIVED_FOR_MESSAGES: 'CONVERSATION.SET_STATUS_RECEIVED_FOR_MESSAGES',
    SET_POPOVER_ID: 'CONVERSATION.SET_POPOVER_ID',
}