export const friendActions = {
    SET_SELECT_ITEM_TAB_TWO: 'FRIEND.SET_SELECT_ITEM_TAB_TWO',
    SET_PENDING_INVITATION: 'FRIEND.SET_PENDING_INVITATION',
    SET_LIST_FRIEND: 'FRIEND.SET_LIST_FRIEND',
    SET_IS_FRIEND: 'FRIEND.SET_IS_FRIEND',
    SET_IS_NOT_FRIEND: 'FRIEND.SET_IS_NOT_FRIEND',
}