export const modalActions = {
    SET_SHOW_MODAL_FIND_FRIEND: 'MODAL.SET_SHOW_MODAL_FIND_FRIEND',
    SET_HIDE_MODAL_FIND_FRIEND: 'MODAL.SET_HIDE_MODAL_FIND_FRIEND',
    SET_SHOW_MODAL_INFO: 'MDOAL.SET_SHOW_MODAL_INFO',
    SET_SHOW_MODAL_UPDATE_INFO: 'MODAL.SET_SHOW_MODAL_UPDATE_INFO',
    SET_HIDE_MODAL_INFO: 'MDOAL.SET_HIDE_MODAL_INFO',
    SET_HIDE_MODAL_UPDATE_INFO: 'MODAL.SET_HIDE_MODAL_UPDATE_INFO',
    SET_SHOW_MODAL_CREATE_GROUP: 'MODAL.SET_SHOW_MODAL_CREATE_GROUP',
    SET_HIDE_MODAL_CREATE_GROUP: 'MODAL.SET_HIDE_MODAL_CREATE_GROUP'
}