export const modalActions = {
    SET_SHOW_MODAL_ADD_FRIEND: 'MODAL.SET_SHOW_MODAL_ADD_FRIEND',
    SET_HIDE_MODAL_ADD_FRIEND: 'MODAL.SET_HIDE_MODAL_ADD_FRIEND',
    SET_SHOW_MODAL_INFO: 'MDOAL.SET_SHOW_MODAL_INFO',
    SET_SHOW_MODAL_UPDATE_INFO: 'MODAL.SET_SHOW_MODAL_UPDATE_INFO',
    SET_HIDE_MODAL_INFO: 'MDOAL.SET_HIDE_MODAL_INFO',
    SET_HIDE_MODAL_UPDATE_INFO: 'MODAL.SET_HIDE_MODAL_UPDATE_INFO'
}