export const tabsActions = {
    SET_MAIN_TAB: 'TAB.SET_MAIN_TAB',
    SET_COUNT_ANNOUNCE_MESSAGE: 'TAB.SET_COUNT_ANNOUNCE_MESSAGE',
    SET_SHOW_TAB_ONE: 'TAB.SET_SHOW_TAB_ONE',
    SET_SHOW_TAB_TWO: 'TAB.SET_SHOW_TAB_TWO',
    SET_SHOW_TAB_THREE: 'TAB.SET_SHOW_TAB_THREE',
    SET_CLOSE_TAB_ONE: 'TAB.SET_CLOSE_TAB_ONE',
    SET_CLOSE_TAB_TWO: 'TAB.SET_CLOSE_TAB_TWO',
    SET_CLOSE_TAB_THREE: 'TAB.SET_CLOSE_TAB_THREE',
}